
site_name: Rodash Documentation
site_url: https://codekingdomsteam.github.io/rodash/
repo_name: CodeKingdomsTeam/rodash
repo_url: https://github.com/CodeKingdomsTeam/rodash

theme:
  name: material
  palette:
    primary: 'Grey'
    accent: 'Blue'

nav:
  - Home: index.md
  - Guide:
      - Arrays: guide/arrays.md
  - API Reference:
      - Arrays: api/Arrays.md
      - Async: api/Async.md
      - Classes: api/Classes.md
      - Functions: api/Functions.md
      - Strings: api/Strings.md
      - Tables: api/Tables.md

extra_css:
  - rodocs.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
